config/routes.rb
Rails.application.routes.draw do
   
  post 'likes/:post_id/create',   to: 'likes#create'
  post "likes/:post_id/destroy" => "likes#destroy"

  get  '/signup',  to: 'users#new'
  post  '/signup',  to: 'users#create'
  get  "posts/:id/edit" => "posts#edit"
  post 'users/:id' => 'users#update'
  post "users/:id/destroy" => "users#destroy"
  resources :users  
  get '/test/login', to:'login#test_login_form'
  get '/login', to: 'login#login_form'
  post '/login', to: 'login#login'
  delete "/logout", to: "login#logout"
  
  get "users/:id/likes" => "users#likes"
  
  get '/new', to: 'posts#new'
  post 'posts/:id' => 'posts#update'
  post "posts/:id/destroy" => "posts#destroy"
  resources :posts
  
  root 'home#top'
  get  '/about',   to: 'home#about'
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  validates :user_id, {presence: true}
  validates :post_id, {presence: true}
end

app/models/post.rb
class Post < ApplicationRecord
    validates :content, presence: true,
                      length: { maximum: 140 }
                      
  def user
    return User.find_by(id: self.user_id)
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  enum gender: { man: 1, woman: 2 }
  
  validates :name, {presence: true}
  validates :email, {presence: true, uniqueness: true}
  
  def posts
    return Post.where(user_id: self.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
   before_action :set_current_user
  
  def set_current_user
    @current_user = User.find_by(id: session[:user_id])
  end
  
  def authenticate_user
    if @current_user == nil
      flash[:notice] = "ログインが必要です"
      redirect_to("/login")
    end
  end
  
  def forbid_login_user
    if @current_user
      flash[:notice] = "すでにログインしています"
      redirect_to("/posts/index")
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :forbid_login_user, {only: [:top]}
  
  def top
  end
  
  def about
  end 
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  
  def create
    @like = Like.new(user_id: @current_user.id, post_id: params[:post_id])
    @like.save
    redirect_to("/posts/#{params[:post_id]}")
  end
  
  def destroy
    @like = Like.find_by(user_id: @current_user.id, post_id: params[:post_id])
    @like.destroy
    redirect_to("/posts/#{params[:post_id]}")
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  before_action :forbid_login_user, {only: [:new, :create, :login_form, :login]}
  
  def login_form
  end
  
  def test_login_form
  end
  
  def login
    @user = User.find_by(email: params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      flash[:notice] = "ログインしました"
      redirect_to("/posts")
    else
      @error_message = "メールアドレスまたはパスワードが間違っています"
      @email = params[:email]
      @password = params[:password]
      render("login/login_form")
    end
  end
  
  def logout
    session[:user_id] = nil
    flash[:notice] = "ログアウトしました"
    redirect_to("/login")
  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user
  
  
  def index
    @posts = Post.all.order(created_at: :desc)
  end
  
  
  def show
    @post = Post.find_by(id: params[:id])
    @user = User.find_by(id: @post.user_id)
    @likes_count = Like.where(post_id: @post.id).count
  end
  
  
  def new
    @post = Post.new
  end
  
  
  def create
    @post = Post.new(content: params[:content],
                     user_id: @current_user.id)
    if @post.save
    redirect_to("/posts")
    else
    render("posts/new")
    end
  end
  
  
  def edit
    @post = Post.find_by(id: params[:id])
  end
  
  
   def update
    @post = Post.find_by(id: params[:id])
    @post.content = params[:content]
    if @post.save
      flash[:notice] = "投稿を編集しました"
      redirect_to("/posts")
    else
      render("posts/edit")
    end
   end
  
  
  def destroy
    @post = Post.find_by(id: params[:id])
    @post.destroy
    redirect_to("/posts")
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user, {only: [:index, :show, :edit, :update]}
  before_action :forbid_login_user, {only: [:new, :create, :login_form, :login]}
  before_action :ensure_correct_user, {only: [:edit, :update]}
  
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(name: params[:name],email: params[:email],password: params[:password])
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "ユーザー登録が完了しました"
      redirect_to("/users/#{@user.id}")
    else
      render("signup")
    end
  end
  
  def show
    @user = User.find_by(id: params[:id])
  end
  
  def index
    @users = User.all
  end
  
  def edit
    @user = User.find_by(id: params[:id])
  end
  
  def update
    @user = User.find_by(id: params[:id])
    @user.name = params[:name]
    @user.email = params[:email]
    
    if params[:image]
      @user.image_name = "#{@user.id}.jpg"
      image = params[:image]
      File.binwrite("public/user_images/#{@user.image_name}", image.read)
    end
    
    if @user.save
      flash[:notice] = "ユーザー情報を編集しました"
      redirect_to("/users/#{@user.id}")
    else
      render("users/edit")
    end
  end
  
  
  def destroy
    @user = User.find_by(id: params[:id])
    @user.destroy
    flash[:notice] = "ユーザーを削除しました"
    redirect_to("/users")
  end
  
  def likes
    @user = User.find_by(id: params[:id])
    @likes = Like.where(user_id: @user.id)
  end
  
   def ensure_correct_user
    if params[:id].to_i != @current_user.id
      flash[:notice] = "権限がありません"
      redirect_to("/posts/index")
    end
   end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def gravatar_for(user)
    gravatar_id  = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user)
    gravatar_id  = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/home/about.html.erb
<h1>あなたの健康をみなさんとシェアしませんか?</h1>


<p>トレーニング内容や睡眠時間をみんなで報告しあって楽しみ会いましょう！！</p>

app/views/home/top.html.erb
<div class="wrapper">
   <div class="column cat1">
      <h1>運動と健康を</br>みんなで共有するアプリ</br>「ヘルRepo」</h1>
   </div>
   <div class="column cat2">
      <h3>食事や運動の記録を発信</h3>
      <h3>あなたの健康をシェアしませんか</h3>
      <p>ヘルRepoを始めよう</p>
      <button type="button" class="btn btn-primary btn-lg "><%= link_to "アカウント作成",signup_path, :style=>"color:white;" %></button>
      <button type="button" class="btn btn-outline-primary btn-lg"><%= link_to "ログイン",login_path %></button>
   </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ヘルRepo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>
   <div class="header">
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
      <h5 class="my-0 mr-md-auto font-weight-normal"><%= link_to "ヘルRepo", root_path, id: "logo", :style=>"color:black;" %></h5>
      <nav class="my-2 my-md-0 mr-md-3">
       <% if @current_user %>
        <a class="p-2 text-dark" ><%= link_to "ユーザー一覧",   users_path, :style=>"color:black;" %></a>
        <a class="p-2 text-dark" ><%= link_to "投稿一覧",   posts_path, :style=>"color:black;" %></a>
        <a class="p-2 text-dark" ><%= link_to "投稿",   new_path, :style=>"color:black;" %></a>
        <a class="p-2 text-dark" ><%= link_to(@current_user.name, "/users/#{@current_user.id}") %>さん</a>
        <a class="p-2 text-dark" ><%= link_to("ログアウト", "/logout", method: :delete) %></a>
       <% else %>
        <a class="p-2 text-dark" ><%= link_to "登録",   signup_path, :style=>"color:black;" %></a>
        <a class="p-2 text-dark" ><%= link_to "ログイン",   login_path, :style=>"color:black;" %></a>
        <a class="p-2 text-dark" ><%= link_to "テストログイン", "/test/login", :style=>"color:#C0C0C0;" %></a>
       <% end%>
      </nav>
    </div>
   </div>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
  </body>

</html>

app/views/login/login_form.html.erb
<div class="col-md-4 offset-md-4 text-center pt-5">
   <% if @error_message %>
    <div class="form-error">
     <%= @error_message %>
    </div>
   <% end %>
   <%= form_tag("/login") do %>
     <p>メールアドレス</p>
     <input name="email"value="<%= @email %>">
     <p>パスワード</p>
     <input type="password" name="password"value="<%= @password %>">
     <input type="submit" value="ログイン">
   <% end %>
</div>

app/views/login/test_login_form.html.erb
<div class="col-md-4 offset-md-4 text-center pt-5">
   <% if @error_message %>
    <div class="form-error">
     <%= @error_message %>
    </div>
   <% end %>
   <%= form_tag("/login") do %>
     <p>メールアドレス</p>
     <input name="email"value="test@test.com">
     <p>パスワード</p>
     <input type="password" name="password"value="1234">
     <input type="submit" value="ログイン">
   <% end %>
</div>

app/views/posts/edit.html.erb
<div class="col-md-4 offset-md-4 text-center pt-5">
   <%= form_tag("/posts/#{@post.id}") do %>
     <textarea name="content"><%= @post.content %></textarea>
     <input type="submit" value="編集">
   <% end %>
</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <div class="posts-index-item">
    <%= link_to gravatar_for(post.user),  "/users/#{post.user.id}" %>
    <%= link_to(post.user.name, "/users/#{post.user.id}") %>
    <%= link_to(post.content, "/posts/#{post.id}") %>
  </div>
<% end %>

app/views/posts/new.html.erb
<div class="col-md-4 offset-md-4 text-center pt-5">
   <%=form_tag("/posts") do %>
     <textarea name="content"><%= @post.content %></textarea>
     <input type="submit" value="投稿する">
   <% end %>
</div>

app/views/posts/show.html.erb
<h1>
 <%= gravatar_for @user %>
 <%= link_to(@user.name, "/users/#{@user.id}") %>
</h1>
<%= @post.content %>
<%=link_to("編集","#{@post.id}/edit") %>
<%= link_to("削除", "/posts/#{@post.id}/destroy", {method: "post"}) %>

<% if Like.find_by(user_id: @current_user.id, post_id: @post.id) %>
   <%= link_to("/likes/#{@post.id}/destroy", {method: "post"}) do %>
      <span class="fa fa-heart like-btn-unlike"></span>
   <% end %>
<% else %>
   <%= link_to("/likes/#{@post.id}/create", {method: "post"}) do %>
      <span class="fa fa-heart like-btn"></span>
   <% end %>
<% end %>
<%= @likes_count %>

app/views/users/edit.html.erb
<div class="col-md-4 offset-md-4 text-center pt-5">
   <%= form_tag("/users/#{@user.id}") do %>
     <p>ユーザー名</p>
     <input name="name" value="<%= @user.name %>">
     <p>メールアドレス</p>
     <input name="email"value="<%= @user.email %>">
     <p>パスワード</p>
     <input type="password" name="password" value="<%= @user.password %>">
     <input type="submit" value="編集">
   <% end %>
</div>

app/views/users/index.html.erb
<% @users.each do |user| %>
  <div class="posts-index-item">
    <%= gravatar_for user %>
    <%= link_to(user.name, "/users/#{user.id}") %>
  </div>
<% end %>

app/views/users/likes.html.erb
      <h2><%= @user.name %></h2>
      <p><%= @user.email %></p>
      <% if @user.id == @current_user.id %>
        <%= link_to("編集", "/users/#{@user.id}/edit") %>
      <% end %>
    
    <ul class="user-tabs">
      <li><%= link_to("投稿", "/users/#{@user.id}") %></li>
      <li class="active"><%= link_to("いいね!", "/users/#{@user.id}/likes") %></li>
    </ul>
    
    <% @likes.each do |like| %>
      <% post = Post.find_by(id: like.post_id) %>
       <%= link_to(post.user.name, "/users/#{post.user.id}") %>
      <%= link_to(post.content, "/posts/#{post.id}") %>

    <% end %>

app/views/users/new.html.erb
<div class="col-md-4 offset-md-4 text-center pt-5">
   <%= form_tag("/signup") do %>
     <p>ユーザー名</p>
     <input name="name" value="<%= @user.name %>">
     <p>メールアドレス</p>
     <input name="email"value="<%= @user.email %>">
     <p>パスワード</p>
     <input type="password" name="password" value="<%= @user.password %>">
     <input type="submit" value="登録">
   <% end %>
</div>

app/views/users/show.html.erb
<%= gravatar_for @user %>
<%= @user.name %>
<% if @user.id == @current_user.id %>
<%=link_to("編集","#{@user.id}/edit") %>
<%=link_to("削除","#{@user.id}/destroy", {method: "post"}) %>
<% end %>
    <ul class="user-tabs">
      <li class="active"><%= link_to("投稿", "/users/#{@user.id}") %></li>
      <li><%= link_to("いいね!", "/users/#{@user.id}/likes") %></li>
    </ul>
    
    <% @user.posts.each do |post| %>
    　<div class="posts-index-item">
      　<%= link_to(post.content, "/posts/#{post.id}") %>
      </div>
    <% end %>